# Supabase 설정
SUPABASE_URL= "https://xwighaogaagsxphbjzjk.supabase.co"
SUPABASE_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3aWdoYW9nYWFnc3hwaGJqemprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODc3MjMsImV4cCI6MjA3MTM2MzcyM30.O0a8_imLT8kYjpKN5Ogc37BNpN_HNYAzJA9SYbd7VBQ"
CLIENT_ID = "509718433777-a2sttkik29nee0c4d7m8rgvkgvrh9l0p.apps.googleusercontent.com"
CLIENT_SECRET = "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"