supabase_url = "https://xwighaogaagsxphbjzjk.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3aWdoYW9nYWFnc3hwaGJqemprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODc3MjMsImV4cCI6MjA3MTM2MzcyM30.O0a8_imLT8kYjpKN5Ogc37BNpN_HNYAzJA9SYbd7VBQ"
